name: BAndC

options:
  minimumXcodeGenVersion: 2.17
  deploymentTarget: 
    iOS: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true
  defaultConfig: Debug
  developmentLanguage: ru

fileGroups:
  - BAndC

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: 1
    ENABLE_TESTABILITY: YES
    INFOPLIST_FILE: BAndC/Info.plist
  configs:
    Debug:
      ENABLE_TESTABILITY: YES
      SWIFT_COMPILATION_MODE: singlefile
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      VALIDATE_PRODUCT: NO
    Release:
      ENABLE_TESTABILITY: NO
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
      VALIDATE_PRODUCT: YES

targets:

  BAndC:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    scheme:
      testTargets:
      - BAndCTests
    sources:
      - path: BAndC
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        PRODUCT_BUNDLE_IDENTIFIER: "DanilaG.B-C"
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1.0.0
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 3TNZ35SGHD
        DEFINES_MODULE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.self.XcodeGenDemo
        XCODEGEN_STATE: YES
        PRODUCT_NAME: "$(TARGET_NAME)"
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS:
        - "$(inherited)"
        - "@executable_path/Frameworks"
    preBuildScripts:
    - script: '$SRCROOT/Scripts/swift_gen.sh $SRCROOT/Modules'
      name: Swift Gen
    - script: ${PODS_ROOT}/SwiftLint/swiftlint --fix && ${PODS_ROOT}/SwiftLint/swiftlint
      name: Swift Lint
  
  BAndCTests:
    type: bundle.unit-test
    platform: iOS
    scheme:
      testTargets:
      - BAndCTests
    sources:
      - path: BAndCTests
    dependencies:
      - target: BAndC
