name: Unit Tests

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  unit_tests:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Setup
        run: ./Scripts/ci_setup.sh

      - name: Project generation
        run: ./Scripts/generate.sh ./Modules ./Scripts

      - name: Run Tests
        run: bundle exec fastlane unit_test
